services:
  # Rails APIサーバー
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: kaikai_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    stdin_open: true
    tty: true

  # React フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: kaikai_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
  node_modules:
